services:
  postgres:
    image: bitnami/postgresql:latest
    user: root # must grant root user for accessing data directory below
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg-data:/bitnami/postgresql # Map local ./pg-data folder to PostgreSQL data directory for persisting data when restarting
    ports:
      - "5432:5432"
